const unitPrice = 1000;
const days = 30;

const quantity = document.getElementById("quantity");
const totalPrice = document.getElementById("totalPrice");

quantity.addEventListener("input", function(){

    let q = parseInt(quantity.value) || 0;

    if(q < 0){
        alert("Quantity cannot be negative");
        quantity.value = 0;
        q = 0;
    }

    let total = unitPrice * q * days;

    totalPrice.value = total;

    if(total > 1000){
        alert("You are eligible for a gift coupon!");
    }

});